export interface RoleProfile {
  id: string;
  label: string;
  summary: string;
  focusAreas: string[];
  keywords: string[];
}

export const ROLE_PROFILES: RoleProfile[] = [
  {
    id: "software-engineer",
    label: "Software Engineer",
    summary:
      "Full-stack engineers with strong fundamentals across algorithms, system design, and modern web development tooling.",
    focusAreas: ["data structures", "system design", "backend services", "CI/CD"],
    keywords: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "Express",
      "REST",
      "GraphQL",
      "SQL",
      "PostgreSQL",
      "MongoDB",
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Testing",
      "Unit Tests",
      "System Design",
      "Microservices",
      "Data Structures",
      "Algorithms",
    ],
  },
  {
    id: "ai-ml-engineer",
    label: "AI / ML Engineer",
    summary:
      "Engineers who build and deploy machine learning systems with emphasis on model development, MLOps, and experimentation.",
    focusAreas: ["model development", "mlops", "data pipelines", "experimentation"],
    keywords: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Deep Learning",
      "Machine Learning",
      "NLP",
      "Computer Vision",
      "Transformers",
      "MLOps",
      "Docker",
      "Kubernetes",
      "AWS",
      "SageMaker",
      "Data Pipelines",
      "Airflow",
      "Kubeflow",
      "Feature Engineering",
      "Experimentation",
      "A/B Testing",
      "Prompt Engineering",
    ],
  },
  {
    id: "data-scientist",
    label: "Data Scientist",
    summary:
      "Analytical professionals who extract insights from data, craft experiments, and support decision-making with statistical rigor.",
    focusAreas: ["statistical analysis", "feature engineering", "experimentation", "stakeholder comms"],
    keywords: [
      "Python",
      "R",
      "SQL",
      "Pandas",
      "NumPy",
      "Matplotlib",
      "Seaborn",
      "Plotly",
      "Statistics",
      "Hypothesis Testing",
      "Machine Learning",
      "Scikit-learn",
      "Feature Engineering",
      "Data Visualization",
      "A/B Testing",
      "Time Series",
      "Forecasting",
      "Business Intelligence",
      "Tableau",
      "Power BI",
      "Storytelling",
    ],
  },
  {
    id: "frontend-engineer",
    label: "Frontend Engineer",
    summary:
      "Interface specialists who deliver accessible, performant, and delightful web experiences with modern UI frameworks.",
    focusAreas: ["accessibility", "performance", "component systems", "UX collaboration"],
    keywords: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind",
      "CSS",
      "HTML",
      "Accessibility",
      "Design Systems",
      "UI Components",
      "Storybook",
      "Testing Library",
      "Cypress",
      "Webpack",
      "Vite",
      "Performance Optimization",
      "Responsive Design",
      "UX Collaboration",
      "Figma",
      "Animation",
    ],
  },
  {
    id: "backend-engineer",
    label: "Backend Engineer",
    summary:
      "Service-oriented engineers focused on scalable APIs, databases, and infrastructure reliability.",
    focusAreas: ["distributed systems", "observability", "databases", "security"],
    keywords: [
      "Node.js",
      "Express",
      "Go",
      "Java",
      "Spring Boot",
      "Microservices",
      "REST",
      "GraphQL",
      "gRPC",
      "AWS",
      "Azure",
      "GCP",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "Cassandra",
      "CI/CD",
      "Terraform",
      "Monitoring",
      "Observability",
      "Security",
    ],
  },
];

export function getRoleProfile(roleId: string): RoleProfile {
  return ROLE_PROFILES.find((role) => role.id === roleId) ?? ROLE_PROFILES[0];
}


